In [33]:
import pandas as pd
import numpy as np

In [34]:
class Perceptron(object):

    """Perceptron classifier.

    Parameters
    ------------
    
    eta : float
      Learning rate (between 0.0 and 1.0)
    n_iter : int
      Passes over the training dataset.
    random_state : int
      Random number generator seed for random weight
      initialization.

    Attributes
    -----------

    w_ : 1d-array
      Weights after fitting.
    errors_ : list
      Number of misclassifications (updates) in each epoch.
    """

    def __init__(self, eta=0.01, n_iter=50, random_state=1):
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state

    def fit(self, X, y):
        
        """Fit training data.
        Parameters
        ----------

        X : {array-like}, shape = [n_samples, n_features]
          Training vectors, where n_samples is the number of samples and
          n_features is the number of features.
          
        y : array-like, shape = [n_samples]
          Target values.
          
        Returns
        -------
        
        self : object
        """

        rgen = np.random.RandomState(self.random_state)
        self.w_ = rgen.normal(loc=0.0, scale=0.01, size=1 + X.shape[1])
        self.errors_ = []

        for _ in range(self.n_iter):
            errors = 0

            for xi, target in zip(X, y):
                update = self.eta * (target - self.predict(xi))
                self.w_[1:] += update * xi
                self.w_[0] += update
                errors += int(update != 0.0)
            self.errors_.append(errors)

        return self

    def net_input(self, X):

        """Calculate net input"""
        return np.dot(X, self.w_[1:]) + self.w_[0]



    def predict(self, X):

        """Return class label after unit step"""
        return np.where(self.net_input(X) >= 0.0, 1, -1)

In [35]:
cols = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'label']
df = pd.read_csv('iris_dataset.csv', names = cols)

In [36]:
df.head()

sepal_length  sepal_width  petal_length  petal_width        label
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [37]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [38]:
df['label'] = np.where(df['label'] == 'Iris-setosa', 1 , -1)

In [39]:
data = df.values[:100, :]

In [40]:
np.random.seed(1)
np.random.shuffle(data)

In [41]:
X = data[:, :-1]
y = data[:, -1]

In [42]:
X[:5]

array([[5.5, 2.4, 3.8, 1.1],
       [5.4, 3. , 4.5, 1.5],
       [5.5, 4.2, 1.4, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [5. , 2.3, 3.3, 1. ]])

In [43]:
y[:5]

array([-1., -1.,  1., -1., -1.])

In [44]:
n = 10
X_train = X[:n]
y_train = y[:n]
X_test = X[n:]
y_test = y[n:]

In [45]:
np.average(X_train), np.average(y_train)

(3.1449999999999996, -0.4)

In [46]:
np.average(X_test), np.average(y_test)

(3.0441666666666665, 0.044444444444444446)

In [47]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((10, 4), (10,), (90, 4), (90,))

In [48]:
y_pred == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [49]:
X_test

array([[5.8, 2.6, 4. , 1.2],
       [5.1, 3.4, 1.5, 0.2],
       [6.3, 3.3, 4.7, 1.6],
       [6.9, 3.1, 4.9, 1.5],
       [6.4, 3.2, 4.5, 1.5],
       [5.2, 4.1, 1.5, 0.1],
       [5.4, 3.4, 1.5, 0.4],
       [5.1, 3.8, 1.9, 0.4],
       [6. , 2.9, 4.5, 1.5],
       [5.4, 3.7, 1.5, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [6.1, 2.8, 4.7, 1.2],
       [6.2, 2.9, 4.3, 1.3],
       [6. , 2.2, 4. , 1. ],
       [5.1, 3.8, 1.5, 0.3],
       [5. , 3.2, 1.2, 0.2],
       [5.6, 2.7, 4.2, 1.3],
       [5.2, 3.5, 1.5, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [4.4, 3. , 1.3, 0.2],
       [5.8, 2.7, 4.1, 1. ],
       [5.7, 2.8, 4.1, 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 3. , 4.2, 1.2],
       [5.6, 3. , 4.1, 1.3],
       [5. , 3.5, 1.3, 0.3],
       [5.3, 3.7, 1.5, 0.2],
       [5.2, 2.7, 3.9, 1.4],
       [5.1, 3.3, 1.7, 0.5],
       [4.9, 3.1, 1.5, 0.2],
       [6.7, 3.1, 4.7, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.7, 3. , 5. , 1.7],
       [5.7, 4.4, 1.5, 0.4],
       [6. , 2

In [50]:
y_test

array([-1.,  1., -1., -1., -1.,  1.,  1.,  1., -1.,  1.,  1., -1., -1.,
       -1.,  1.,  1., -1.,  1.,  1.,  1., -1., -1., -1., -1., -1.,  1.,
        1., -1.,  1.,  1., -1., -1., -1.,  1., -1.,  1.,  1., -1.,  1.,
       -1.,  1., -1.,  1.,  1., -1.,  1.,  1., -1.,  1., -1.,  1., -1.,
       -1.,  1.,  1., -1.,  1., -1.,  1., -1., -1.,  1., -1., -1.,  1.,
       -1.,  1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,
       -1., -1.,  1.,  1., -1., -1.,  1., -1.,  1., -1.,  1.,  1.])

In [51]:
model = Perceptron(eta=0.01, n_iter=10)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = sum(y_pred == y_test) / y_test.shape[0]
accuracy

0.7777777777777778

In [52]:
model = Perceptron(eta=0.015, n_iter=10)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = sum(y_pred == y_test) / y_test.shape[0]
accuracy

0.9777777777777777

In [53]:
model = Perceptron(eta=0.02, n_iter=10)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = sum(y_pred == y_test) / y_test.shape[0]
accuracy

1.0